name: CI/CD Pipeline

on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  # Checkout code from repository

    - name: Login to AWS ECR
      uses: aws-actions/amazon-ecr-login@v2  # Automatically log in to ECR

    - name: Build and Push Docker Image
      run: |
        docker build -t 872966921168.dkr.ecr.us-east-1.amazonaws.com/hello-world-app-repo:latest .
        docker push 872966921168.dkr.ecr.us-east-1.amazonaws.com/hello-world-app-repo:latest

    # Optional: Update ECS Service (replace with your specific approach)
    - name: Update ECS Service (Example)  # Replace with your deployment approach
      uses: aws-actions/aws-cli@v2
      with:
        aws-region: us-east-1  # Replace with your AWS region
        commands: |
          aws ecs update-service --cluster hello-world-cluster --service hello-world-app-service --force-new-deployment
